{% set version = "2.1.6" %}

package:
  name: hint
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/69/7d/1c759127d2e576999dd9cd872cd4422548db65b7da63ba528b24950832aa/HiNT-Package-2.1.6.tar.gz
  sha256: 43b16bf2052990f577cba36e5b115bb6fc810f907f840fe7014d74b58df716eb

build:
  number: 0
  noarch: python
  #script: $PYTHON -m pip install --no-deps --ignore-installed --no-cache-dir .
requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - perl >=5
    - R >=3.4
    - multiprocess >=0.70.5
    - numpy >=1.16.1
    - scipy >=1.0.1
    - h5py >=2.8.0
    - pairix >=0.3.6
    - pytabix
    - cooler >=0.8.2
    - pairtools >=0.2.2
    - pandas >=0.23.0
    - scikit-learn >=0.19.1
    - argparse >=1.1
    - openjdk >=8
    - samtools >=1.9
    - tabix
    - bwa >=0.7.16
    - r-mgcv
    - r-strucchange
    - r-Cairo
    - r-doparallel
    - r-foreach

test:
  commands:
    - hint -h

about:
  home: https://github.com/suwangbio/HiNT_py3
  license: MIT
  summary: HiNT is a computational method for detecting copy number variations and translocations from Hi-C data

extra:
  container:
    extended-base: true
